# Generated by Django 5.2.4 on 2025-07-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
