# Generated by Django 5.2.4 on 2025-07-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=8),
        ),
    ]
